[cmake]
version = "3.15"
# subdirs = []
# build-dir = ""
# cpp-flags = []
# c-flags = []
# link-flags = []
# generator = ""
# arguments = []

[project]
name = "searchString"
version = "0.1.0"

# [find-package]

# [fetch-content]

# [options]

[target.searchString]
type = "executable"
sources = ["src/*.cpp"]
include-directories = ["include"]
# alias = ""
# compile-features = []
# compile-definitions = []
# link-libraries = []

[[install]]
targets = ["searchString"]
destination = "${CMAKE_INSTALL_PREFIX}/bin"
